// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1kJ_EjPRghFwHP8igWwTxKrBRXpWql1A',
    appId: '1:713124710857:web:266d9cc7918a4c6df90018',
    messagingSenderId: '713124710857',
    projectId: 'ecommerce-assignment-7bca5',
    authDomain: 'ecommerce-assignment-7bca5.firebaseapp.com',
    storageBucket: 'ecommerce-assignment-7bca5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMXlQb90koa73fl3KtP3wfu0uEH9APyOM',
    appId: '1:713124710857:android:33833f13c02d63c3f90018',
    messagingSenderId: '713124710857',
    projectId: 'ecommerce-assignment-7bca5',
    storageBucket: 'ecommerce-assignment-7bca5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjSgKgp-XwiW-gB49Wx7fap2PyQeunf84',
    appId: '1:713124710857:ios:eb95b8aa3279fd12f90018',
    messagingSenderId: '713124710857',
    projectId: 'ecommerce-assignment-7bca5',
    storageBucket: 'ecommerce-assignment-7bca5.appspot.com',
    iosBundleId: 'com.example.ecommerceAppAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjSgKgp-XwiW-gB49Wx7fap2PyQeunf84',
    appId: '1:713124710857:ios:eb95b8aa3279fd12f90018',
    messagingSenderId: '713124710857',
    projectId: 'ecommerce-assignment-7bca5',
    storageBucket: 'ecommerce-assignment-7bca5.appspot.com',
    iosBundleId: 'com.example.ecommerceAppAssignment',
  );
}
